highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: false
url: http://batchik.net
author: Joseph Batchik

baseurl: /
title: Joseph Batchik's homepage
name: JD Batchik
email: josephbatchik@gmail.com
email_full: mailto:josephbatchik@gmail.com
website: batchik.net
website_full: http://batchik.net
github: JDrit
linkedin: josephbatchik
google_analytics: UA-49487129-1

# needed for travis-ci build
exclude: [vendor]
